name: "Approve test 2"

on: 
  workflow_dispatch:
    inputs:
      greeting:
        description: "greeting"
        type: string

jobs:
  receive-repository-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Receive
        run: |
          greeting=${{ github.event.inputs.greeting }}
          echo $greeting
      - name: checkout
        uses: actions/checkout@v3
      - name: show info
        run: ls